version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.6
    restart: always
    volumes:
      - /Users/jamespeter/Downloads/jones/docker-html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
    ports:
      - 8082:80
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /Users/jamespeter/Downloads/jones/docker-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - back
networks:
  back:

